version: '3.7'
services:
  dnsbl:
    image: mrdockernnm/dns:latest
    volumes:
      - data:/data
    ports:
      - target: 53
        published: ${PORT:-53}
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]      
      interval: 30s
      timeout: 3s
      retries: 10

volumes:
   data:



 







