apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo
spec:
  replicas: 2
  selector:    
    matchLabels:
      app: demo-app      
  template:
    metadata:
      labels:      
        app: demo-app
    spec:
      containers:        
      - name: demo-app      
        image: mrdockernnm/dns:latest
        resources:          
          requests:
            memory: "500Mi"
            cpu: "250m"          
          limits:
            memory: "500Mi"
            cpu: "500m"                        
        ports:
        - containerPort: 53
        
